import turtle

warna_latar_belakang = turtle.Screen().bgcolor('pink')


pena = turtle.Turtle()


pena.pensize(3)

pena.goto(0,50)
pena.right(90)
pena.down()
pena.fillcolor('yellow')
pena.begin_fill()
pena.left(90)
pena.forward(120)
pena.left(45)
pena.forward(50)
pena.left(45)
pena.forward(125)
pena.left(45)
pena.forward(50)
pena.left(45)
pena.forward(220)
pena.left(45)
pena.forward(50)
pena.left(45)
pena.forward(125)
pena.left(45)
pena.forward(50)
pena.left(45)
pena.forward(100)
pena.end_fill()
pena.up()

pena.down()
pena.fillcolor('brown')
pena.begin_fill()
pena.forward(20)

pena.right(90)
pena.forward(50)
pena.right(90)
pena.forward(20)
pena.left(90)
pena.end_fill()
pena.up()
pena.pencolor('red')
pena.goto(-25,70)
pena.left(90)
pena.down()
pena.left(90)
pena.forward(30)
pena.backward(15)
pena.right(90)
pena.forward(30)
pena.left(90)
pena.forward(15)
pena.backward(30)
pena.up()
pena.goto(15, 65)
pena.down()
pena.forward(30)
pena.up()
pena.goto(35, 65)
pena.down()
pena.forward(1)
pena.up()
pena.goto(35,75)
pena.down()
pena.forward(19)
pena.up()
pena.pencolor('black')

pena.goto(10, 115)
pena.down()
pena.pencolor('blue')
pena.right(90)
pena.circle(55, 360)

pena.pencolor('red')

pena.goto(30,125)
for i in range(10):
    pena.left(99)
    pena.forward(40)



turtle.done()